//
//  KiwiComicsAppDelegate.h
//  KiwiComics
//

// This is the start point. Contains mostly autogenerated content.

#import <UIKit/UIKit.h>


@interface KiwiComicsAppDelegate : NSObject <UIApplicationDelegate, UITabBarControllerDelegate> {
    UIWindow *window;
    UITabBarController *tabBarController;
	
    NSManagedObjectModel *managedObjectModel;
    NSManagedObjectContext *managedObjectContext;	    
    NSPersistentStoreCoordinator *persistentStoreCoordinator;
	NSMutableDictionary *managedObjectContexts;
}

@property (nonatomic, retain) IBOutlet UIWindow *window;
@property (nonatomic, retain) IBOutlet UITabBarController *tabBarController;

@property (nonatomic, retain, readonly) NSManagedObjectModel *managedObjectModel;
@property (nonatomic, retain, readonly) NSManagedObjectContext *managedObjectContext;
@property (nonatomic, retain, readonly) NSPersistentStoreCoordinator *persistentStoreCoordinator;
@property (retain, readonly) NSMutableDictionary *managedObjectContexts;

- (NSString *)applicationDocumentsDirectory;
- (NSManagedObjectContext *) managedObjectContextWithID: (NSString *) chapterlink;
@end
